<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7fab5371-bf57-4d11-9f5f-4ff50f07d6fc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexus.Application\Nexus.Application.csproj" />
    <ProjectReference Include="..\Nexus.Infrastructure\Nexus.Infrastructure.csproj" />
  </ItemGroup>

</Project>
